# The Agent class implements the rhetorical validation and refinement component
# of the MIMIC augmentation pipeline. It is responsible for:
#
# 1. Evaluating whether a rephrased EDU preserves the intended rhetorical relation
#    with its paired EDU, using high-level explanations generated by an LLM.
#
# 2. When validation fails (as detected by external classifiers), Agent produces 
#    actionable suggestions that guide how to revise the rephrased EDU 
#    to restore the original rhetorical relationship.
#
# 3. These suggestions are then appended to the dialogue prompts and passed back 
#    to the LLM in a secondary generation step (invoked externally), enabling
#    iterative refinement of the generated EDU.
#
# The refine_EDU() method handles this second-round generation, injecting
# previously collected suggestions into the system/user prompt to produce a
# relation-preserving revision. 
#
# The evaluation() method defines LLM prompts based on the original EDU pair,
# the rephrased version, and the rhetorical relation, asking the model to reason
# about why the new version fails and how it could be improved.
#
# This class supports the EDU Refinement step of MIMIC, ensuring that discourse
# coherence and rhetorical consistency are preserved in LLM-generated augmentations.

import os
from openai import OpenAI


class Agent:

    def __init__(self, model, relation_explanations,
                 client=None, base_url=None, api_key=None):
        self.model = model
        self.client = client or OpenAI(
            base_url=base_url or os.getenv("LLM_BASE_URL"),
            api_key=api_key or os.getenv("LLM_API_KEY", "not-needed"),
        )
        self.relation_explanations = relation_explanations

    def refine_EDU(self, system_prompt, user_prompt, suggestions):
        additional_text = "Additionally, suggestions are provided to assist in the generation process."

        system_prompt += f"\n{additional_text}"

        suggestion_utterances = '\n'.join(suggestions)

        user_prompt += f"\n\nSuggestions:\n{suggestion_utterances}"

        completion = self.client.chat.completions.create(
            model=self.model,
            messages=[
                {"role": "system",
                 "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            temperature=0,
        )

        response = completion.choices[0].message.content.strip('"')

        return response


    def __system_prompt_definition(self, relation_type):

        return f"""
        You are an expert in understanding why a rephrased utterance no longer satisfies the "{relation_type}" relation when compared to another utterance.
        The "{relation_type}" relation is defined as follows:
        "{self.relation_explanations[relation_type]}"

        Given the original pair of utterances that previously satisfied this relation, one of the utterances has now been rephrased. Your task is to provide high-level guidance on how the rephrased utterance should be adjusted to restore the relation, without providing a specific rephrasing. The suggestion should focus on the key aspects that need to be preserved or modified in the rephrased utterance to ensure it aligns with the original utterance in terms of the defined relation.
        """

    def __user_prompt_definition(self, original_utterance_1, original_utterance_2, relation_type, rephrased_utterance):

        return f"""
        You are given the following inputs:

        Original Utterance 1: "{original_utterance_1}"
        Original Utterance 2: "{original_utterance_2}"
        Relation: "{relation_type}"
        Rephrased Utterance: "{rephrased_utterance}"

        The rephrased utterance is a modified version of "{original_utterance_1}", and it no longer satisfies the given relation with "{original_utterance_2}". Your task is to generate a high-level suggestion on how "{rephrased_utterance}" can be improved to restore the relation "{relation_type}" with "{original_utterance_2}".

        Here's what you need to do:
        - Analyze the two original utterances and understand the relation "{relation_type}" between them.
        - Examine "{rephrased_utterance}" and determine why it no longer satisfies the relation with "{original_utterance_2}".
        - Provide a high-level suggestion on how "{rephrased_utterance}" can be modified to restore the relation. Focus on the key aspects that need to be preserved or modified in "{rephrased_utterance}" to ensure it aligns with "{original_utterance_2}" according to the given relation.

        Do not generate a new rephrased utterance, nor reference the current one in your output. Instead, provide concise, one-sentence guidance on how the rephrasing should be approached.
        """

    def evaluation(self, original_utterance_1, original_utterance_2, relation_type, rephrased_utterance):

        system_prompt = self.__system_prompt_definition(relation_type)

        user_prompt = self.__user_prompt_definition(original_utterance_1, original_utterance_2, relation_type, rephrased_utterance)

        completion = self.client.chat.completions.create(
            model = self.model,
            messages = [
                {"role": "system",
                 "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            temperature=0,
        )

        response = completion.choices[0].message.content.strip('"')

        return response